CREATE SEQUENCE OBL_SEQ START
WITH
	1101 INCREMENT BY 1;
CREATE TABLE OBL (OBL INT PRIMARY KEY, NOBL VARCHAR(200));
ALTER TABLE OBL
ALTER COLUMN OBL
SET DEFAULT NEXTVAL('obl_seq');

CREATE TABLE RAJ (RAJ INT PRIMARY KEY, NRAJ VARCHAR(200));

CREATE TABLE CITY (
	CITY_KOD SERIAL PRIMARY KEY,
	NCITY VARCHAR(200),
	KRAJ INT,
	KOBL INT,
	FOREIGN KEY (KRAJ) REFERENCES RAJ (RAJ),
	FOREIGN KEY (KOBL) REFERENCES OBL (OBL)
);

CREATE TABLE TEMP_UPOST (
	REG VARCHAR(200),
	DIST VARCHAR(200),
	SETT VARCHAR(200),
	POSTCODE VARCHAR(200)
);
CREATE TABLE AUP (
	ID SERIAL PRIMARY KEY,
	POSTCODE int,
	CITY int,
	NCITY VARCHAR(200),
	OBL int,
	NOBL VARCHAR(200),
	RAJ int,
	NRAJ VARCHAR(200)	
);
/*----------------------------------------------*/

/*Predfined data*/
COPY TEMP_UPOST (REG, DIST, SETT, POSTCODE)
FROM
	'/tmp/upostdata.csv' DELIMITER ';';
	
COPY OBL (OBL,NOBL)
FROM
	'/tmp/postOBL.csv' DELIMITER ';';
	
COPY RAJ (RAJ, NRAJ)
FROM
	'/tmp/postRAJ.csv' DELIMITER ';';
	
COPY CITY (NCITY, KRAJ, KOBL)
FROM '/tmp/postCityV2.csv'
WITH (FORMAT csv, HEADER false, DELIMITER ',');